name: Test
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: |
        0 0 * * *
jobs:
  test:
    name: Unit test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.17.x, 1.18.x, 1.19.x]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Go test
      run: go test -v
